### ISSUE TITLE
chapter_09/big_final_exercise.md - CR review

### ISSUE THREAD

**Issue by CohenOri** [883G/OLD-Onboarding-Newbies-OLD#12]
I don't think it's a good idea to give such a "freedom" for newbie. Few reasons:
1. Time Estimation - Unique assignment for each teammate make it harder to estimate.
2. Tendency to over complicate or to "force" usage of technologies that doesn't necessarily bring value just to mark some V's required in the exercise - it's also pricey in terms of mentoring - cause he'll have to explain why it's bad architecture.
3. Common exercise - Common "Experience" connects people, we have tendency to bond with someone that did the same "experiment" as we did. "Do you remember this Linear Algebra course with this crazy lecturer?" etc.

I think the exercise you've sent me once is good idea, just make it shorter to fit up to two weeks.

**Comment by shplishka** [comment]
I will estimate the time after the first newbie will do the full process. 
About your another questions - I will guide the mentors to be focus about that..
