### ISSUE TITLE
chapter_00/day_02.md - CR questions

### ISSUE THREAD

**Issue by CohenOri** [883G/OLD-Onboarding-Newbies-OLD#2]
On:
https://github.com/883G/Onboarding-Newbies/blob/main/chapter_00/day_02.md#1-introduction-to-data-pipelines)

Introduction to Data Pipelines, Data Lifecycle in the Unit bullets, I couldn't actually produce an action item, what do you expect to do *exactly* "Walk through the data lifecycle within..." how do you do it?
If we don't want the mentor to work very hard, or the newbie to just read and skip it we need simple to follow action item - like ask what exactly data pipeline X do, and what's its life cycle, what's the data lineage. you can find the DAG defining it in url pipeline.example.com etc.

**Comment by shplishka** [comment]
I will guide the mentor to be focus on that
